### ISSUE TITLE
Support for ecdsa.PublicKey (feature request?)

### ISSUE THREAD

**Issue by ncode** [42wim/vault-plugin-auth-ssh#18]
Would it be possible to implement or accept PRs to add support for ecdsa.PublicKey. My idea is to use it along with https://github.com/FiloSottile/yubikey-agent and use Yubikey 9a slot to interact with vault.

**Comment by 42wim** [comment]
It seems the yubikey-agent also supports rsa. Any reason you want ecdsa?

**Comment by ncode** [comment]
Yubikeys 4/5 only supports [2048 bit RSA](https://github.com/Yubico/yubico-piv-tool/issues/58) :(. The next best option for these devices is ecdsa.

**Comment by 42wim** [comment]
Fixed in v0.3.0

**Comment by ncode** [comment]
> Fixed in v0.3.0 

Thank you!
