### ISSUE TITLE
Use of ssh-agent/SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by DrDaveD** [42wim/vault-plugin-auth-ssh#3]
Thanks a lot for this plugin, I think it's a good start on what I need.  Have you thought about making it work with ssh-agent, by doing a challenge-response via $SSH_AUTH_SOCK?

**Comment by 42wim** [comment]
did you see https://github.com/42wim/vault-plugin-auth-ssh/discussions/2 ?
