### ISSUE TITLE
Support for policy templating

### ISSUE THREAD

**Issue by DrDaveD** [42wim/vault-plugin-auth-ssh#4]
As far as I can tell this currently requires a separate policy for every user.  I would like to be able to take advantage of [policy templating](https://learn.hashicorp.com/tutorials/vault/policy-templating), by configuring a set of user names and assigning each to a public key or keys.  Then depending on which public key is used, it would map to a particular user and that can be encoded into the policy through an entity alias. 

Does that sound like a reasonable addition to you?  I use this feature with the jwt and kerberos builtin vault auth plugins.  There would need to be an additional configuration, not just "public_keys" but a mapping of users to public keys, or probably vice versa.

**Comment by 42wim** [comment]
Sure, is this something you're willing to take a look at?

**Comment by DrDaveD** [comment]
It turns out that the role was already being added to the "name" alias, and I can use role for user name.  By adding the metadata login option as in #8 I can easily use one policy for everything, which is very nice.  I want vault tokens to be limited to a single secret because I pass the tokens on to a server that automatically reads the secret repeatedly.  Each user is allowed to get vault tokens for any of their secrets but each individual token can only get one.
