### ISSUE TITLE
Question on security of login protocol

### ISSUE THREAD

**Issue by DrDaveD** [42wim/vault-plugin-auth-ssh#7]
I'm not sure that allowing the client to choose the nonce that is signed is good security.  That's not the way that other secure protocols such as ssh itself does things.  It allows for reply attacks, if someone is able to somehow eavesdrop or be a man-in-the-middle (which is admittedly difficult with https).  It also allows a client to be lazy and just use the same nonce over and over.   I think the nonce should probably be generated randomly by the server, then the the client send back the signature of that nonce.  I realize that can't be done with just a one-step "login" api, but the vault-plugin-auth-jwt for instance does a two-step authorization, at least in oidc mode.  The client just needs to do two different api calls. 

What do you think?

**Comment by 42wim** [comment]
@DrDaveD yes, you're absolutely correct. It's not in the github version yet, but in our internal version we use the time as nonce (as you can also see in vssh example). We allow a 30s window.

I'll add support for this here soon.

**Comment by DrDaveD** [comment]
Could please go ahead and this, I'd like to use it soon.

I wonder if it makes sense to add a random number in addition to the time, so the nonce can't be easily guessed.

**Comment by DrDaveD** [comment]
On further reflection, I don't think using time as the nonce is sufficiently secure either.  One of the primary reasons why we use vault is to protect long-term secrets by giving out short-term access.  The idea with that is to limit the loss if the short-term secret is compromised.  The problem with the time-based nonce is that it is completely predictable.  If someone gained short-term access to someone's ssh-agent the could quickly generate a file of signatures for times in the future, say one per day or one per week.

No, I think the thing to do is to have another API call that sends a random nonce from the server, and require the client to call login within a few seconds with the same nonce & its signature.

**Comment by 42wim** [comment]
Yes, you are right, if you're using normal public keys (instead of short-lived ssh certificates) and they can access your ssh-agent they can do what you suggest. 
But realistically if someone could've access to your ssh-agent you have bigger problems I think ?

I'm not against implementing this though as it is more secure :)
We could do it with a `vault read auth/ssh/nonce` for example.

**Comment by 42wim** [comment]
I've made a PR to fix this issue.
